### ISSUE TITLE
[Avatar Hider] Gestures, animations and Phys Bones get stuck

### ISSUE THREAD

**Issue by Lupsoris** [SleepyVRC/Mods#15]
Hello,

It's been a long time since Avatar Hider has updated, and it's been a VERY long time since many of us have encountered the same problem: at some point, if the avatars make a gesture or an animation and they are hide, these animations seem to be stucked and continue to play constantly once the avatar is unhided.

It's especially annoying with gestures, since you end up with faces that are completely distorted by blendshapes at too high values that are overrided.

Is this a problem that can be fixed?
This problem has been going on for too long.. ^^'

Thank you,
Lupsoris

**Comment by ljoonal** [comment]
Fixing this isn't a huge priority for myself, since I imagine that a workaround is just to hide&show the avatar. 
Since I've not really come across the behavior lately myself, so haven't reproduced this yet.

Any contributions would be welcome though.

**Comment by Lupsoris** [comment]
Hello,

It's mostly that it's a problem that has been there for a very long time, and that quickly becomes disturbing because you've to hide/show everyone often. But it's a bit random, and maybe related to a less powerful PC for example. What I couldn't confirm.

For now, I notice that this problem is less visible, but still present. There's always an avatar with an open mouth when it's not the case, or some small modified blendshapes.

Now I don't really know how I could help more than that.. ^^' 

Thank you,
Lupsoris

**Comment by Lupsoris** [comment]
Hello, following the new updates, the problem is still present.

Moreover, I could add that the Phys Bones are also broken. If a Phys Bone is fixed at some point, hide, unhide and then reloaded by Avatar Hider, or something similar. This will keep a bad position until manual reload (Safety to Hide, then Safety).

![Capture d’écran 2022-05-16 152048](https://user-images.githubusercontent.com/29005043/168603329-5a202934-31f7-407e-96d2-12536464144c.png)
![Capture d’écran 2022-05-16 152425](https://user-images.githubusercontent.com/29005043/168603335-14ab2aa9-8224-42e1-ba49-8c074d2f8969.png)

Thanks to you,
Lupsoris

**Comment by ljoonal** [comment]
AvatarHider is now maintained at https://github.com/EllyVR/AvatarHider, please open an issue there if this is still relevant with the new version.
