### ISSUE TITLE
[Avatar Hider] Feature Request

### ISSUE THREAD

**Issue by SariellVR** [SleepyVRC/Mods#22]
First of all, please forgive me if this is not the correct way to request a feature but I am new to git and couldn't figure out how else to do it.

Secondly, I want to thank you for this wonderful mod. It is, by far, the most useful and must have mod I have ever seen!

Now, onto my suggestion:

Avatar Hider can currently hide avatars based on distance.
This works very well for general purpose but runs into a bit of trouble when the user is watching an area of interest from afar, for example the stage at an event.

I am proposing adding a cone shaped area of effect in addition to the disc shaped one which is currently implemented (disc in horizontal plane, I am not sure if it is a cylinder or a sphere in 3d space)
Of course, the orientation of this cone shaped "far sight" would be best tied to the position in the game world (so adjustable by moving/rotating with sticks) and not tied to head movement directly.

Right now, when attending events, I simply "show avatar" on the people on stage. If the number of performers is small, this works out great. But when there are many of them and they keep going on and off stage, I have no other option than to show all of them and take a performance hit or not show any of them.

Well, hopefully this binocular view won't be too much of a chore to implement, but I understand that the implementation effort could outweigh the gains.

**Comment by ljoonal** [comment]
AvatarHider is now maintained at https://github.com/EllyVR/AvatarHider, please open an issue there if this is still relevant with the new version.
