### ISSUE TITLE
Avatar Hider - Breaks VRLabs World Physics Fix

### ISSUE THREAD

**Issue by JustSleightly** [SleepyVRC/Mods#9]
This is an issue that came about in version 1.3 of AH when it was still maintained by loukylor. 

### The Issue:
Any prefab or system that takes advantage of the VRLabs World Physics Fix cannot be viewed properly by any user that has Avatar Hider installed, regardless of what settings or features are enabled in the .config. The rigidbodies will instead spazz/flicker out and fly all over. This is not viewable locally if you have Avatar Hider installed and are looking at your own World Physics Fix.

I've tested it specifically with both versions 1.2.6 and 1.3, and it did not appear until 1.3, so it likely has to do with the introduction of the Limit Audio Distance implementation.

I've brought it up with loukylor in the past not realizing he had moved on and archived, so I dropped it for now and had only just heard of it being picked back up here by Myrkur. Below are some screenshots that may prove relevant or helpful.

![image](https://user-images.githubusercontent.com/75227041/146850736-b9d5b311-03ae-4369-9986-e75a862e9a75.png)

![image](https://user-images.githubusercontent.com/75227041/146850790-7afe5790-e181-49d4-bfa3-1128bc735954.png)

I understand that Avatar Hider itself works fine and that this isn't a critical issue across the board, but it has definitely been a big pain for me and my users and any other physics prefabs, who want to show off their cool new toy to their friends, but considering how prominent Avatar Hider is, a huge percentage of people can't see anything. And I can't exactly ask people to just rollback their AH one version very easily either.

I'll gladly volunteer my [product](https://github.com/JustSleightly/SleightlyBall) and myself for QA or other testing if you ever want to consider fixing this. Feel free to contact me on Discord at JustSleightly#zerozerozero1

**Comment by ljoonal** [comment]
The comparison between the breaking tags is then https://github.com/SleepyVRC/Mods/compare/AH-1.2.6...AH-1.3.0 in case someone else wonders over to this issue an wants to fix it.

Quickly glancing at it, doesn't seem like there could be too many things that are breaking it.
I don't personally encounter these systems too often though, so won't promise prioritizing this issue too much myself.
I'll try to have a look though eventually if no-one else opens a PR before then.
